# Generated by Django 6.0.3 on 2026-04-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("manager", "Manager"), ("designer", "Designer")],
                db_index=True,
                default="manager",
                help_text="Rôle métier utilisé dans Design Workflow.",
                max_length=16,
                verbose_name="Rôle",
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="role",
            field=models.CharField(
                choices=[("manager", "Manager"), ("designer", "Designer")],
                db_index=True,
                default="manager",
                help_text="Rôle métier utilisé dans Design Workflow.",
                max_length=16,
                verbose_name="Rôle",
            ),
        ),
    ]
