from django.urls import path

from .views import (
    ChatMessageDeleteView,
    ChatMessageReadView,
    ChatMessagesView,
    ChatThreadListView,
    DashboardSummaryView,
    NotificationListView,
    NotificationReadView,
    ProjectDetailView,
    ProjectListCreateView,
    TaskArchiveView,
    TaskCompletionView,
    TaskCoverImageView,
    TaskAttachmentDetailView,
    TaskAttachmentsView,
    TaskChecklistDetailView,
    TaskChecklistListView,
    TaskCommentsView,
    TaskLabelListCreateView,
    TaskDetailView,
    TaskListCreateView,
    TaskReassignView,
    TaskStatusView,
    TaskTimeEntriesView,
    TimeReportView,
    WorkloadView,
)

app_name = "design_workflow"

urlpatterns = [
    path("dashboard/summary/", DashboardSummaryView.as_view(), name="dashboard-summary"),
    path("projects/", ProjectListCreateView.as_view(), name="projects"),
    path("projects/<int:pk>/", ProjectDetailView.as_view(), name="project-detail"),
    path("tasks/", TaskListCreateView.as_view(), name="tasks"),
    path("labels/", TaskLabelListCreateView.as_view(), name="labels"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/<int:pk>/status/", TaskStatusView.as_view(), name="task-status"),
    path("tasks/<int:pk>/complete/", TaskCompletionView.as_view(), name="task-complete"),
    path("tasks/<int:pk>/archive/", TaskArchiveView.as_view(), name="task-archive"),
    path("tasks/<int:pk>/cover/", TaskCoverImageView.as_view(), name="task-cover"),
    path("tasks/<int:pk>/checklist/", TaskChecklistListView.as_view(), name="task-checklist"),
    path("tasks/<int:pk>/checklist/<int:item_id>/", TaskChecklistDetailView.as_view(), name="task-checklist-detail"),
    path("tasks/<int:pk>/attachments/", TaskAttachmentsView.as_view(), name="task-attachments"),
    path("tasks/<int:pk>/attachments/<int:attachment_id>/", TaskAttachmentDetailView.as_view(), name="task-attachment-detail"),
    path("tasks/<int:pk>/reassign/", TaskReassignView.as_view(), name="task-reassign"),
    path("tasks/<int:pk>/comments/", TaskCommentsView.as_view(), name="task-comments"),
    path("tasks/<int:pk>/time-entries/", TaskTimeEntriesView.as_view(), name="task-time-entries"),
    path("workload/", WorkloadView.as_view(), name="workload"),
    path("reports/time/", TimeReportView.as_view(), name="time-report"),
    path("notifications/", NotificationListView.as_view(), name="notifications"),
    path("notifications/<int:pk>/read/", NotificationReadView.as_view(), name="notification-read"),
    path("chat/threads/", ChatThreadListView.as_view(), name="chat-threads"),
    path("chat/threads/<int:pk>/messages/", ChatMessagesView.as_view(), name="chat-messages"),
    path("chat/messages/<int:pk>/read/", ChatMessageReadView.as_view(), name="chat-message-read"),
    path("chat/messages/<int:pk>/delete/", ChatMessageDeleteView.as_view(), name="chat-message-delete"),
]
