from django.urls import path

from .views import (
    AttachmentAnnotationListView,
    ChatMessageDecisionView,
    ChatMessageDeleteView,
    ChatMessageReadView,
    ChatMessageReactionView,
    ChatMessageReminderView,
    ChatMessageUpdateView,
    ChatMessagesView,
    ChatThreadListView,
    DashboardSummaryView,
    NotificationListView,
    NotificationActionView,
    NotificationPreferenceView,
    NotificationReadView,
    NotificationSnoozeView,
    ProjectDetailView,
    ProjectListCreateView,
    SavedViewDetailView,
    SavedViewListCreateView,
    TaskArchiveView,
    TaskArtifactVersionListView,
    TaskCompletionView,
    TaskCoverImageView,
    TaskAttachmentDetailView,
    TaskAttachmentsView,
    TaskChecklistDetailView,
    TaskChecklistGroupListView,
    TaskChecklistListView,
    TaskCommentsView,
    TaskLabelListCreateView,
    TaskDetailView,
    TaskListCreateView,
    TaskReassignView,
    TaskReorderView,
    TaskReviewView,
    TaskStatusView,
    TaskTimeEntriesView,
    TimeReportView,
    WorkloadView,
    WorkflowAnalyticsReportView,
    WorkspaceSearchView,
)

app_name = "design_workflow"

urlpatterns = [
    path("dashboard/summary/", DashboardSummaryView.as_view(), name="dashboard-summary"),
    path("views/", SavedViewListCreateView.as_view(), name="saved-views"),
    path("views/<int:pk>/", SavedViewDetailView.as_view(), name="saved-view-detail"),
    path("search/", WorkspaceSearchView.as_view(), name="workspace-search"),
    path("projects/", ProjectListCreateView.as_view(), name="projects"),
    path("projects/<int:pk>/", ProjectDetailView.as_view(), name="project-detail"),
    path("tasks/", TaskListCreateView.as_view(), name="tasks"),
    path("tasks/reorder/", TaskReorderView.as_view(), name="task-reorder"),
    path("labels/", TaskLabelListCreateView.as_view(), name="labels"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/<int:pk>/status/", TaskStatusView.as_view(), name="task-status"),
    path("tasks/<int:pk>/complete/", TaskCompletionView.as_view(), name="task-complete"),
    path("tasks/<int:pk>/archive/", TaskArchiveView.as_view(), name="task-archive"),
    path("tasks/<int:pk>/cover/", TaskCoverImageView.as_view(), name="task-cover"),
    path("tasks/<int:pk>/checklists/", TaskChecklistGroupListView.as_view(), name="task-checklists"),
    path("tasks/<int:pk>/checklist/", TaskChecklistListView.as_view(), name="task-checklist"),
    path("tasks/<int:pk>/checklist/<int:item_id>/", TaskChecklistDetailView.as_view(), name="task-checklist-detail"),
    path("tasks/<int:pk>/attachments/", TaskAttachmentsView.as_view(), name="task-attachments"),
    path("tasks/<int:pk>/attachments/<int:attachment_id>/", TaskAttachmentDetailView.as_view(), name="task-attachment-detail"),
    path("tasks/<int:pk>/review/", TaskReviewView.as_view(), name="task-review"),
    path("tasks/<int:pk>/versions/", TaskArtifactVersionListView.as_view(), name="task-artifact-versions"),
    path("attachments/<int:pk>/annotations/", AttachmentAnnotationListView.as_view(), name="attachment-annotations"),
    path("tasks/<int:pk>/reassign/", TaskReassignView.as_view(), name="task-reassign"),
    path("tasks/<int:pk>/comments/", TaskCommentsView.as_view(), name="task-comments"),
    path("tasks/<int:pk>/time-entries/", TaskTimeEntriesView.as_view(), name="task-time-entries"),
    path("workload/", WorkloadView.as_view(), name="workload"),
    path("reports/time/", TimeReportView.as_view(), name="time-report"),
    path("reports/workflow/", WorkflowAnalyticsReportView.as_view(), name="workflow-analytics-report"),
    path("notifications/", NotificationListView.as_view(), name="notifications"),
    path("notifications/preferences/", NotificationPreferenceView.as_view(), name="notification-preferences"),
    path("notifications/<int:pk>/read/", NotificationReadView.as_view(), name="notification-read"),
    path("notifications/<int:pk>/snooze/", NotificationSnoozeView.as_view(), name="notification-snooze"),
    path("notifications/<int:pk>/action/", NotificationActionView.as_view(), name="notification-action"),
    path("chat/threads/", ChatThreadListView.as_view(), name="chat-threads"),
    path("chat/threads/<int:pk>/messages/", ChatMessagesView.as_view(), name="chat-messages"),
    path("chat/messages/<int:pk>/read/", ChatMessageReadView.as_view(), name="chat-message-read"),
    path("chat/messages/<int:pk>/delete/", ChatMessageDeleteView.as_view(), name="chat-message-delete"),
    path("chat/messages/<int:pk>/edit/", ChatMessageUpdateView.as_view(), name="chat-message-edit"),
    path("chat/messages/<int:pk>/react/", ChatMessageReactionView.as_view(), name="chat-message-react"),
    path("chat/messages/<int:pk>/decision/", ChatMessageDecisionView.as_view(), name="chat-message-decision"),
    path("chat/messages/<int:pk>/reminders/", ChatMessageReminderView.as_view(), name="chat-message-reminder"),
]
