# Generated by Codex for design workflow card extras and chat.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("design_workflow", "0001_initial"),
    ]

    operations = [

        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(choices=[("task_assigned", "Task assigned"), ("task_reassigned", "Task reassigned"), ("task_due_soon", "Task due soon"), ("task_overdue", "Task overdue"), ("task_comment", "Task comment"), ("task_status", "Task status"), ("task_blocked", "Task blocked"), ("chat_message", "Chat message")], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="taskactivity",
            name="action_type",
            field=models.CharField(choices=[("created", "Created"), ("updated", "Updated"), ("status_changed", "Status changed"), ("priority_changed", "Priority changed"), ("due_date_changed", "Due date changed"), ("reassigned", "Reassigned"), ("comment_added", "Comment added"), ("time_logged", "Time logged"), ("project_created", "Project created"), ("project_updated", "Project updated"), ("project_archived", "Project archived"), ("label_updated", "Label updated"), ("checklist_updated", "Checklist updated"), ("attachment_added", "Attachment added"), ("task_archived", "Task archived")], max_length=32),
        ),
        migrations.CreateModel(
            name="TaskLabel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("color", models.CharField(default="#111827", max_length=16)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.AddField("task", "archived", models.BooleanField(db_index=True, default=False)),
        migrations.AddField("task", "archived_at", models.DateTimeField(blank=True, null=True)),
        migrations.AddField("task", "labels", models.ManyToManyField(blank=True, related_name="tasks", to="design_workflow.tasklabel")),
        migrations.AddIndex("task", models.Index(fields=["archived", "status"], name="design_work_archive_e1c81c_idx")),
        migrations.CreateModel(
            name="TaskChecklistItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("done", models.BooleanField(db_index=True, default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="completed_task_checklist_items", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_task_checklist_items", to=settings.AUTH_USER_MODEL)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="checklist_items", to="design_workflow.task")),
            ],
            options={"ordering": ("sort_order", "created_at")},
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="design_workflow/task_attachments/%Y/%m/")),
                ("name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=120)),
                ("size", models.PositiveIntegerField(default=0)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="design_workflow.task")),
                ("uploaded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="uploaded_task_attachments", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="ChatThread",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(choices=[("public", "Public"), ("private", "Private")], db_index=True, max_length=16)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("participants", models.ManyToManyField(blank=True, related_name="design_chat_threads", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-updated_at",)},
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(blank=True)),
                ("read_by", models.ManyToManyField(blank=True, related_name="read_design_chat_messages", to=settings.AUTH_USER_MODEL)),
                ("sender", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="design_chat_messages", to=settings.AUTH_USER_MODEL)),
                ("thread", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="design_workflow.chatthread")),
            ],
            options={"ordering": ("created_at",)},
        ),
        migrations.CreateModel(
            name="ChatMessageAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="design_workflow/chat_attachments/%Y/%m/")),
                ("name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=120)),
                ("size", models.PositiveIntegerField(default=0)),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="design_workflow.chatmessage")),
            ],
            options={"ordering": ("created_at",)},
        ),
    ]
