# Generated by Django 6.0.3 on 2026-05-04 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design_workflow", "0009_premium_board_review_notifications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatthread",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_threads",
                to="design_workflow.project",
            ),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_threads",
                to="design_workflow.task",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="source_chat_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tasks",
                to="design_workflow.chatmessage",
            ),
        ),
        migrations.AlterField(
            model_name="chatthread",
            name="kind",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("project", "Project"),
                    ("task", "Task"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="chatthread",
            index=models.Index(
                fields=["kind", "project"], name="design_work_kind_d52d8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatthread",
            index=models.Index(
                fields=["kind", "task"], name="design_work_kind_6f1985_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatthread",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "project"), ("project__isnull", False)),
                fields=("kind", "project"),
                name="unique_design_project_chat_thread",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatthread",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "task"), ("task__isnull", False)),
                fields=("kind", "task"),
                name="unique_design_task_chat_thread",
            ),
        ),
    ]
