# Generated by Django 6.0.3 on 2026-05-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design_workflow", "0010_chatthread_project_chatthread_task_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("task_assigned", "Task assigned"),
                    ("task_reassigned", "Task reassigned"),
                    ("task_due_soon", "Task due soon"),
                    ("task_overdue", "Task overdue"),
                    ("task_comment", "Task comment"),
                    ("task_status", "Task status"),
                    ("task_blocked", "Task blocked"),
                    ("chat_message", "Chat message"),
                    ("review_requested", "Review requested"),
                    ("workflow_digest", "Workflow digest"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
