# Generated by Django 6.1.1 on 2026-09-15 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_existing_label_owners(apps, schema_editor):
    TaskLabel = apps.get_model("design_workflow", "TaskLabel")
    HistoricalTaskLabel = apps.get_model("design_workflow", "HistoricalTaskLabel")
    Task = apps.get_model("design_workflow", "Task")
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)

    fallback_user = User.objects.order_by("pk").first()
    if TaskLabel.objects.exists() and fallback_user is None:
        raise RuntimeError("Cannot assign existing task labels without a user account.")

    TaskLabel.objects.filter(color__iexact="#111827").update(color="#4f46e5")
    HistoricalTaskLabel.objects.filter(color__iexact="#111827").update(
        color="#4f46e5"
    )

    owner_by_label_id = {}
    for label in TaskLabel.objects.all():
        first_task = Task.objects.filter(labels=label).order_by("created_at", "pk").first()
        owner_id = first_task.created_by_id if first_task else fallback_user.pk
        label.created_by_id = owner_id
        label.save(update_fields=("created_by",))
        owner_by_label_id[label.pk] = owner_id

    for label_id, owner_id in owner_by_label_id.items():
        HistoricalTaskLabel.objects.filter(
            id=label_id,
            created_by__isnull=True,
        ).update(created_by_id=owner_id)
    if fallback_user is not None:
        HistoricalTaskLabel.objects.filter(created_by__isnull=True).update(
            created_by_id=fallback_user.pk,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("design_workflow", "0013_merge_duplicate_public_chat_threads"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltasklabel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tasklabel",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="design_task_labels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicaltasklabel",
            name="name",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="tasklabel",
            name="name",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="historicaltasklabel",
            name="color",
            field=models.CharField(default="#4f46e5", max_length=16),
        ),
        migrations.AlterField(
            model_name="tasklabel",
            name="color",
            field=models.CharField(default="#4f46e5", max_length=16),
        ),
        migrations.RunPython(assign_existing_label_owners, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="tasklabel",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="design_task_labels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="tasklabel",
            constraint=models.UniqueConstraint(
                fields=("created_by", "name"),
                name="unique_design_task_label_owner_name",
            ),
        ),
    ]
