# Generated by Django 6.1.1 on 2026-10-03 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design_workflow", "0017_attachment_bigint_sizes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True,
                related_name="collaborating_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
