# Generated by Django 6.1.1 on 2026-10-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design_workflow", "0020_chat_reminder_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltaskattachment",
            name="thumbnail",
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="taskattachment",
            name="thumbnail",
            field=models.ImageField(
                blank=True, upload_to="design_workflow/attachment_thumbnails/%Y/%m/"
            ),
        ),
    ]
