# Generated by Django 6.1.1 on 2026-10-06 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ws", "0002_wsmaintenancestate_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangelogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, unique=True
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Title — French"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Title — English"
                    ),
                ),
                (
                    "changes_fr",
                    models.TextField(
                        blank=True,
                        help_text="One change per line. Plain language, no HTML.",
                        verbose_name="Changes — French",
                    ),
                ),
                (
                    "changes_en",
                    models.TextField(
                        blank=True,
                        help_text="One change per line. Plain language, no HTML.",
                        verbose_name="Changes — English",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Published"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Changelog entry",
                "verbose_name_plural": "Changelog",
                "ordering": ("-date", "-pk"),
            },
        ),
    ]
