# Generated by Django 6.1.1 on 2026-10-06 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ws", "0004_seed_changelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="changelogentry",
            name="version",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Release version. Leave empty for older, unversioned entries.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(0|[1-9]\\d{0,5})\\.(0|[1-9]\\d{0,5})\\.(0|[1-9]\\d{0,5})\\Z",
                        "Use a release version such as 1.2.0 (three numbers, up to six digits each).",
                    )
                ],
            ),
        ),
    ]
